import { Model } from '@nozbe/watermelondb';
import { field, relation, date, json } from '@nozbe/watermelondb/decorators';
import { sanitizer } from '../utils';

export default class Message extends Model {
    static table = 'messages';

    static associations = {
        rooms: { type: 'belongs_to', key: 'rid' }
    };

    @field('msg') msg;

    @field('ack') ack;

    @field('alias') alias;

    @field('type') type;
    // one of type
    // "REGULAR" : A regular message created in the channel.
    // "REPLY" : A message in a reply thread. Messages created with parent_id are automatically of this type.
    // "DELETED" : A soft deleted message.
    // "SYSTEM" : A message generated by a system event, like updating the channel or muting a user.
    // "ERROR" : An error message generated as a result of a failed command. It is also ephemeral, as it is not stored in the channel history and is only delivered to one user.

    @date('_updated_at') _updated_at;

    @json('edited_by', sanitizer) edited_by;

    @relation('rooms', 'rid') room;

    @json('attachments', sanitizer) attachments;

    @json('reactions', sanitizer) reactions;

    @field('emoji') emoji;

    @json('replies', sanitizer) replies;

    @json('mentions', sanitizer) mentions;

    @field('isDeleted') isDeleted;

    @json('receivers', sanitizer) receivers;

    @json('seens', sanitizer) seens;

    getMessage() {
        return {
            id: this._raw.id,
            msg: this.msg,
            ack: this.ack,
            _updated_at: this._updated_at,
            edited_by: this.edited_by,
            rid: this._raw.rid
        };
    }
}
