export const ENUM_STACK = {
    SPLASH_STACK: 'SPLASH_STACK',
    HOME_STACK: 'HOME_STACK',
    CALL_STACK: 'CALL_STACK',
    CHAT_STACK: 'CHAT_STACK',
    LOGIN_AUTHEN: 'LOGIN_AUTHEN',
    FISRT_LOGIN_SHOW_ON_BOARDING: 'FISRT_LOGIN_SHOW_ON_BOARDING',
    AUDIO_CALL_STACK: 'AUDIO_CALL_STACK'
};

export const LOG_TYPE = {
    DEBUG: 0,
    WARNING: 1,
    ERROR: 2
};
